# アメリカの経営システム {#usa}

## アメリカの文化・政治・経済 {#usa-out}

### 文化 {#us-culture}

1. 多民族国家 　

　WASP
人種構成　多様だが初期の移民の文化の影響が強い構成表
wasp ケネディ・オバマ大統領1階waspが大統領今後白人が減り、他の人種が増加するだろうとされている主にヒスパニック・アジア移民流入、出生率高い影響力が低下した白人の不満トランプ大統領支持
max weber プロテスタンティズムの倫理と資本主義の精神
権力格差低い→権力格差を受け入れがたい個人主義高い→みんなと同じであることに価値はない、ユニークさを求められる○就職　経理、営業、マーケティング、広告×就社企業とは雇用契約を結ぶ(仕事が特定される)→個人の成果重視縁故<個人の能力　転職が多い
男性主義比較的高い→アメリカンドリーム「物質的成功」剛の価値が評価される一方で女性の社会進出は多く、地位も高い
不確実性回避低い→開拓者精神
長期指向低い→短期的利益を追求、時間に厳しい、すぐに親しくなる、率直に話す

2. 



### 政治システム・法制度 {#us-politics}

　二大政党制
　契約社会・条文の細かさ
政治システム・法制度民主主義・三権分立　政治が安定しているため、政権交代があっても政策継続性が期待できる→長期の経営計画が立てやすい
政権交代(大統領選挙4年ごと)企業設備投資(5〜10年計画)政策の予測可能性高い→投資促進
アメリカ政府　○自由競争　×独占　→ 巨大企業「分割」
低文脈→法律（契約）が詳細、教科書が厚い

### 経済システム {#us-economy}

　アームズレングス
　独占を嫌う社会
　流動性の高い経済（労働・金融）
　市場中心の金融システムについては、appendix
　発達した金融市場（市場中心）:証券市場での資金調達が多い、証券取引が活発であり、ベンチャーキャピタルが発達
　図表あり（間接金融）

高い経済的自由市場競争が激しい、起業、買収、合併(M&A)、倒産、外国企業の国内進出が多い→不確実性回避が低い理由柔軟な労働市場不況時のレイオフ(一時解雇)が容易→不確実性回避が低い理由

図表あり
解雇しやすい　必要なときすぐ採用できる労働者側再就職しやすい、再就職先は元の会社より儲かっているクビになることは怖いことではない、しかも職種ごとに採用経済全体の効果:不況業種から好況業種や人材が移動
不確実性回避低い再チャレンジが容易な社会制度柔軟な労働市場（日本:終身雇用）発達した金融市場（日本:銀行中心）

　証券市場（株式市場、債券市場）：家計の金融資産（日本：15-20%、アメリカ：50%）
　低い政府関与　経済規模に比べ政府支出は少ない、国営企業も少ない、年金や健康保険は他国に比べ民間部門が大きい
　米国：健康保険（医療保険）　個人で加入（給与の一部として支給）⇔失業すると失う
　結果の不平等　機会の平等は高く求められるが、家計の所得・資産の不平等は大きい
　不確実性回避低い：労働市場、金融市場

## アメリカ企業の経営者 {#us-manager}
<br>

### 選抜・移動 {#us-selection}
　新卒採用や昇進などの労働システムのあり方（ジョブ型・メンバーシップ型）についてはAppendixでまとめる。
　平均56歳、男性が多い、富裕層（出身）が多い、が、相対的に減少している（＝多様化）
　女性経営者はまだ少ないが、大卒・MBA卒は男性より女性が多いので見込みはある。
　所有と経営の分離　プロ経営者（A社社長退任→B社社長就任）外部登用が3-4割・ヘッドハンティング
　　　　　　　　　　専門経営者⇔サラリーマン経営者（平社員から内部昇進）
　所有者（owner）＝株式保有者（出資者）　と　経営者が異なる

　民間と政府の相互移動（回転ドア）　民間と政府で相互に転職することがあり、民間経営者が政府高官になることがある　官僚から民間への転職「天下り」が多かった日本と対照的
　まとめると、若い、移動が多い、プロ経営者が多い

　アメリカ人が非英語圏で経営することは少ない

### 報酬 {#us-payment}

<!--
　大企業経営者　11.3億円　日本は1億円以上出す企業は少ない
　ストックオプション　一定期間内にあらかじめ決められた価格で所属する会社から自社株式を購入できる権利
　高報酬はプロ経営者が多いことが背景にある　外部登用の際、成功報酬としてストックオプションが付与されることが多い
-->

* **ペイレシオ**：企業の経営トップの報酬が従業員の賃金の何倍かを示す数値をペイレシオ（pay ratio）という。  

ペイレシオ
日本経済新聞2018年5月13日　米報酬、企業差が鮮明「CEOは社員の何倍か」開示
https://www.dir.co.jp/report/column/20170921_012304.html

https://www.cnn.co.jp/business/35124268.html

https://www.meti.go.jp/meti_lib/report/2015fy/000134.pdf

業績連動報酬
日本経済新聞2018年12月6日　きょうのことば
https://www.nikkei.com/article/DGXKZO38600620V01C18A2EA2000/?n_cid=SPTMG053


日本経済新聞2018年12月12日　CEO報酬、アメリカは日本の6倍　首位は117億円 

英ＣＥＯの給料、一般社員の１６７年分　男女間でも格差
(https://www.cnn.co.jp/business/35124268.html)


表3.1　ダウ平均構成30社の社長の年収（1～5位）

| 順位 |社長(CEO)名|社名|年収|前期比増減率|株式報酬の割合|従業員の年収に対する倍率|株価騰落率|
|:-----|:----------|:---|:--:|:----------:|:------------:|:------------------:|:------------:|
|   1  |ジョン・ドナホー	       |ナイキ	                       |58.3億円|	ー   |83% |1935倍	|28%|
|   2  |サティア・ナデラ	       |マイクロソフト	               |48.3億円|	3%	 |69% |257倍	|52%|
|   3  |ジェームズ・ダイモン    |JPモルガン・チェース	         |34.5億円|	0%	 |79% |395倍	|▲10%|
|   4  |アレックス・ゴースキー  |ジョンソン・エンド・ジョンソン |32.2億円|	17%	 |61% |365倍	|7%|
|   5  |マイケル・ワース	       |シェブロン	                   |31.6億円|	▲12% |52% |184倍	|▲29%|


注）1ドル＝109円で換算  
出所）日経ヴェリタス（日経電子版）[^1]

[^1]:日経ヴェリタス（日経電子版） 2021年6月27日「社長の給料、日米で16倍差　米国平均は23億円」

### 教育 {#us-education}

　高学歴　学問としての経営学
　学部の22%、修士課程の25%に経営学専攻がある
　図表あり
　A：営業担当社員←必要な能力（＝学歴）提示
　B：営業担当管理職←必要な能力（＝学歴）提示
　昇進は内部外部に差がない

## アメリカ企業のマネジメント {#us-management}
<br>

### 計画 {#us-plan}

　予算：売上－費用＝利益（見込み・目標）　年間予算、月次予算
　中・長期計画　中期（3-5年）長期（10年）
　生産販売計画⇒投資計画・事業展開（戦略）
　1980年代　コンサルティング業発展（財務会計・税務、生産、情報システム）
　新しい経営手法を積極的に導入
　他国の傾向　助言サービスが必要ないのでコンサルティング業の発展速度は遅い

### 組織化 {#us-organization}
　
　図表
　分権化（権限移譲）デュポンやGMが事業部制を採用した　1920年代から進む
　1914年第一次世界大戦　欧州が戦場　1920年代以降経済の中心がヨーロッパからアメリカへ

　企業レベルの組織変化　買収、合併、企業分割　→　敵対的買収もしばしば行われる
　図表
　最適な工場数？
　企業①が企業②を買収
　企業①がB工場を②に売却、企業②にD工場を①に売却
　M&Aアドバイザー（投資銀行）

### 指揮・調整 {#us-command}

　直接的表現　契約書が詳細に作成される（低文脈社会）　雇用契約・業績評価が詳細になる

### 統制 {#us-control}

　株式会社　出資者が株式を保有　株主が株主総会で取締役を選任　取締役は取締役会で経営をチェック　代表取締役は社長のことが多い
　外部統制　敵対的買収による経営解任のリスクが高まる
　内部統制　取締役（会）の役割：所有者（株主）に代わって、マネジメント・統制する→雇用、助言、評価、報酬、人事（管理職の配転）
　図表
　買収されるほど株価が下落しないように経営努力する←統制

柔軟な労働市場　人材の流動性が高い
金融市場　売買が活発　流動性が高い



