# 日本企業の経営システム {#japan}

- 本章の構成は、以下のとおりです。

  - \@ref(japan-external)では、日本企業の経営システムの外部要因として、\@ref(japan-culture)文化、\@ref(japan-politics)政治システム・法制度、\@ref(japan-economy)経済システムを整理します。
  
  - \@ref(japan-manager)では、日本企業の経営者の特徴として、\@ref(japan-selection)選抜・移動、\@ref(japan-payment)報酬、\@ref(japan-education)教育を整理します。
  
  - \@ref(japan-management)では、日本企業の経営プロセスを\@ref(japan-plan)計画、\@ref(japan-organization)組織化、\@ref(japan-command)指揮・調整、\@ref(japan-control)統制を整理します。
  
  
## 日本の文化・政治・経済 {#japan-external}

- 本節では、日本企業経営の外部要因として、日本の文化・政治・経済を確認します。

  - まず、経営学の源流として、[文化](#japan-culture)を整理します。

  - 次に、[政治システム・法制度](#japan-politics)を整理します。

  - 最後に、[経済システム](#japan-economy)を整理します。

### 文化 {#japan-culture}

#### 仏教・儒教の影響

- 

- 儒教的価値観には、集団主義、序列、秩序、法への順守、権力への服従、調和の重視、教育への敬意などがあります。

  - 社会を安定させる

- 特定の価値観に合わせて社会システム（政治・経済）が一度形成されると、人々は行動をそれに適合させようとします。時代が流れて価値観が薄れたとしても、社会システムは簡単には変化しません。

- 

1. 儒教・仏教の影響 ？　

　ところで、第\@ref(usa)章では  
　島国（逃げられない・関係性ガバナンス）
　


2. 恥の文化

　菊と刀
　同質性圧力

序列意識
　組織の格付・順位を気にする→東大・京大がトップ、大企業が中小企業よりステータスが高い
学歴重視
受験勉強激しく、学習塾に通う
→いい大学が有名企業への就職につながる（企業も成績や専攻よりも大学名を見る）
自意識
他人からどう見られるかが重要、恥を避けようとする→西洋人は罪を避けようとする
裁判
問題解決時に対立（裁判）を避けようとする
→国民1人あたり弁護士数は先進国で最も少ない
終身雇用
他国に比べ、転職が少ない年功賃金が影響

資産・所得
分配
平等主義的→CEOと平均的社員の格差は10.5対1で、先進国で最も低い

　
#### Hofstedeの指標

- 権力格差は54で中程度、世界的にみても中間に位置します。

  - 大企業は階層主義的（高い権力格差の傾向）ですが、その一方で企業の意思決定は合意志向（低い権力格差の傾向）のため、権力格差は中程度になったと考えられます。

- 個人主義は46で中程度、世界的にみても中間に位置します。
集団意識
会社員は自分を職種よりも勤務する会社で認識しようとする→大企業男性社員はほぼ終身雇用
→就職というより就社、企業も「系列・グループ」という形で集団意識が見られる
中程度→集団意識はあるが、家族優先ではない

  - ○就職　経理、営業、マーケティング、広告×就社
  
  - 企業とは雇用契約を結ぶ(仕事が特定される)→個人の成果重視縁故<個人の能力　転職が多い
  
  - 日本は終身雇用によって集団意識が企業単位で形成されているため、転職へのハードルが高くなっている（リスクが高い）と考えられます。

> 日本人の多くは、自分は集団主義的ではなくどちらかといえば個人主義的だと思ってるし、集団主義的な生き方よりも個人主義的な生き方のほうが望ましいと思っている。だけど他の人たちは自分とは違って集団主義的な生き方を好ましいと思っていて、だから個人主義的な行動をとるとそうした人たちから悪く思われてしまうと思い込んでいる。（山岸・ブリントン (2010, p.244)）

- 男性性は95と高く世界的にみても高い位置にあります。

  - 競争を好む長時間労働・仕事中毒


- 不確実性回避92と世界的にみても高い位置にあります。

  - 安定・継続を好み、リスクや変化に不安を感じる

> 生き方と社会のあり方はやっぱり切り離せなくて、嫌われたっていいじゃないかと思えるためには、ほんとうに嫌われても困らないような環境が必要。つまりセカンドチャンスがないとダメ。ぼくが言いたいのは、いろんなオプションがないと、ともかくリスクを避けようというふうにしか行動できない。人間関係にしても、仕事や他のことを決定することに関してもそうだと思う。（山岸・ブリントン (2010, pp.146-147)）


- 長期指向（88）

  - 高い→長期的関係を重視する

  
  - 初対面の相手に親しく（柔らかく）接することが多く、笑顔を絶やさず、すぐにファーストネームで呼び始めたりします。（Meyer. (2014, 日本語版 p.217)）
  
    - ただし、このように友好的であることは必ずしも友情とはイコールではなりません。
    
    - *長期的「関係」がない人とうまくやっていくスキル　山岸「信頼」*

- 充足的 42
中程度

- 日本は世界で最も高文脈な社会です。（Meyer. (2014, 日本語版 p.59)）

  - 国民は世界各国からの移民で構成されています。移民はそれぞれ別々の歴史、別々の言葉、別々のバックグラウンドを持っています。
  
  - 建国以来の歴史も短いため、共有する文脈が少なくなります。

  - メッセージを伝える際は曖昧さや誤解が生じる余地をなくして、できるだけはっきりと明快に伝えることが、コミュニケーションの基本になります。




### 政治システム・法制度 {#japan-politics}

1. 1955年体制 　

　自民党長期政権
民主主義国家だが、事実上、一党の長期政権　

2. 官僚制
首相や議会の力は他国よりも弱く、官僚が強い力を持つ
法案をほとんどを官僚が作成し、議員立法は少ない

　縦割り行政
　

　政官財トライアングル
政府（≒自民党）、官僚、財界（経団連等）が、政策の（事前）調整を行う　
高い
長期志向

### 経済システム {#japan-economy}

1. 系列
個々の企業は独立しているものの、緊密な関係（資本、人事、技術、取引）にある企業群
市場経済の各企業よりも近いが、単一の企業よりも緩やかな関係
高い長期志向

　系列には水平的系列と垂直的系列の2種類がある。
水平的系列
多角化した（戦前の）財閥系（三菱、三井、住友等）企業が、戦後に銀行を中心にまとまった
→相互に株式を持ち合って買収を妨げる、毎月社長が会合を持って情報交換する
集団意識
垂直的系列
大企業が部品を供給する関係会社をまとめた（日立、松下→パナソニック、トヨタ等）
→親会社が子会社を、子会社が孫会社の株式を保有する

2. メインバンクシステム

　銀行中心の金融システムについては、appendix

3. 政府主導型経済成長
政官財トライアングルで調整された政策によって、ターゲット産業を中心に経済成長を図る
　産業政策
政府（経済企画庁）が策定した計画にもとづき、通商産業省（現在の経済産業省）が各産業の振興（また円滑な縮小）を目的に策定する政策
保護貿易、研究開発等への補助金、資金調達の援助



https://media.startup-db.com/research/marketcap-global

労働組合
企業内労働組合で、 1950年代以降激しい対立はほとんどない→労働争議で失われる時間は先進国中最少
市民団体
環境問題を除き、圧力団体は少ない

二重構造
非効率的な国内向けサービス業
（通信・小売・金融）・農業
効率的で世界的大企業が含まれる輸出向け製造業（自動車、電機、機械）



<span style="font-size: 150%">**参考文献**</span>

Hall, Edward T. (1977). Beyond culture. Anchor Books.（岩田慶治・谷泰（訳）(1993)『文化を超えて　新装版』阪急コミュニケーションズ.）

Hofstede, G, G. J. Hofstede, and M. Minkov (2010). Cultures and Organizations: Software of the Mind, Third Edition. McGraw-Hill Education.（日本語版　岩井八郎・岩井紀子（訳）(2013)『多文化世界　違いを学び未来への道を探る　原書第3版』有斐閣.）

Meyer, E. (2014). The Culture Map: Breaking Through the Invisible Boundaries of Global Business. PublicAffairs.（日本語版　樋口武志（訳）・田岡恵（監訳）(2015)『異文化理解力』英治出版.）



## 日本企業の経営者 {#japan-manager}

### 選抜・移動 {#japan-selection}

年齢
任期
常務50代、社長59歳欧米では49-50歳で社長就任
社長として6.3年、その後2/3が会長になる、業績不振によって退任を強いられることは少ない
社会的背景
大卒、大学院卒も一般的、工学か社会科学の学位
外資系を除き、ほとんど日本人
先進国で大企業の女性経営者の比率は一番低い
同質性
日本社会の同質性が、経営者の背景やキャリアパスの均一性につながる
例外：盛田昭夫、松下幸之助、本田宗一郎

　新卒採用や昇進などの労働システムのあり方（ジョブ型・メンバーシップ型）についてはAppendixでまとめる。
　サラリーマン社長の同質性（学歴重視の結果でもある）
　ダイバーシティに遅れる

表3.1　日本経団連正副会長19名（2018年6月）のプロフィール
```{r, echo = FALSE, fig.align="center"}
keidanren <- read.csv("keidanren.csv", header = TRUE)
knitr::kable(keidanren)
```

出所）日本経済新聞[^1]、日本産業新聞[^2]

[^1]:日本経済新聞朝刊 2018年6月18日「変わる経団連、変われぬ経団連」  
[^2]:日経産業新聞 2018年6月22日「経団連　この恐るべき同質集団」


### 報酬 {#japan-payment}

　差がつくのが遅い昇進

　緩やかな賃金カーブ

日本経済新聞2018年6月29日　「1億円プレーヤー」500人超　役員報酬、欧米型に 

https://www.tsr-net.co.jp/news/analysis/20210624_06.html

先進国の中でも低い
業績連動ボーナスを実施する企業は少ない（増えてはいる）
ゴルフ会員権など非金銭的報酬がある
http://toyokeizai.net/articles/-/177387?page=2


### 教育 {#japan-education}

- 小熊 (2019)は、上掲の日経新聞記事が「卒業した大学名は詳細に記されているが、学部や専攻については何も述べていない」ことを指摘し、日本社会は「何を学んだかが重要でない学歴重視」であるとしている。

  - 情報の経済学におけるシグナリングという概念を使うと、学歴重視には合理性があるとされる。

https://gendai.ismedia.jp/articles/-/71570

https://blogos.com/article/460720/

大企業・政府は有名大学から大量に採用する
←受験によって選抜が済んでいる
個人の資質（責任感、規律等）を重視し、大学の専攻はさほど重要視しない
学問としての経営学
経営学科が経済学部にあることがある、
→学問としての認識は海外より低い
大卒の1/5は経済・経営系（アメリカと同様）
大学院
16人に1人がビジネススクール卒業生（アメリカは4人に1人）→MBAが出世や昇給の近道となっていない
社内教育
OJT中心に積極的に行う、日立や松下（パナソニック）などは社内に教育機関をもっている



<span style="font-size: 150%">**参考文献**</span>

Hall, Edward T. (1977). Beyond culture. Anchor Books.（岩田慶治・谷泰（訳）(1993)『文化を超えて　新装版』阪急コミュニケーションズ.）

Hofstede, G, G. J. Hofstede, and M. Minkov (2010). Cultures and Organizations: Software of the Mind, Third Edition. McGraw-Hill Education.（日本語版　岩井八郎・岩井紀子（訳）(2013)『多文化世界　違いを学び未来への道を探る　原書第3版』有斐閣.）

Meyer, E. (2014). The Culture Map: Breaking Through the Invisible Boundaries of Global Business. PublicAffairs.（日本語版　樋口武志（訳）・田岡恵（監訳）(2015)『異文化理解力』英治出版.）



## 日本企業のマネジメント {#japan-management}

日本的経営　アベグレン

### 計画 {#japan-plan}
<br>
経営理念（ビジョン）
欧米企業と比べ長期計画は厳密でないが、経営理念が強く働いている→綿密な長期計画を策定するよりも、ビジョン・方向性を示す
短期・中期計画
綿密な計画を立てる
情報収集
欧米企業よりも熱心に情報収集（海外の新聞等からの外国の産業、貿易などの情報）を行う
→系列企業（総合商社）が集めた情報を共有する
日本貿易振興会（JETRO）、大使館員も国内企業のために、競争企業や市場動向に関する情報を収集している
日本企業の強み
絶え間ない改善（コスト削減・品質向上）、柔軟な生産体制、市場化への時間短縮
独自性よりも模倣
ビジネスの中心は模倣で、独特な製品や戦略は少ない→独特な製品や戦略がある企業は例外
長期的戦略よりも、短期の生産・販売計画に重心
多角化
欧米企業よりも多角化は少ない
→多角化する場合も親会社の部門独立が多く、他社の買収は少ない（徐々に増えつつある）

### 組織化 {#japan-organization}

　人事ローテーション
　
　柔軟な組織（多能工）
組織を越えて、協力ができる→ジョブ・ローテーションが可能にしている（誰もが複数の能力を身につけている）
曖昧な役割分担
協力の一方で、責任も分担される
→共同責任は無責任

中央集権
意思決定は中央（経営陣）に集中する
海外現地法人の経営も日本人、かつ本社の判断を仰ぐ
系列
別法人である系列企業においても、グループ本社が調整
→ある企業の経営が悪くなると、系列企業同士で協力する（従業員の融通、取引価格の調整）

### 指揮・調整 {#japan-command}

- 階層主義的

- 合意志向

この組み合わせは例外的

　稟議
　
　根回し
　
利益追求（だけ）の主体ではなく、雇用を確保し社員の生活を向上させることを基本的目的としている
　集団意識

モチベーションは世界的にみて高い水準
社員も仕事を自分の労働力の販売とは考えない
恥の文化
恥を避けようとし、周囲を失望させないようにする
残業
早く帰ると仕事に熱心でないようにみえる
高い男性主義
報酬
職位や生産性でなく年功で決まる（最初の10-20年）、社宅、福利厚生、住宅購入補助のほか、結婚支援もある
ほめられることが苦手
お世辞と聞こえ、それが不信につながることもある→減点主義が多い（できないことを注意する）
高い不確実性回避
日本的リーダー
合意形成者
必要な資質：公正さ、寛大さ、慎重さ、冷静さ
合意形成システム
各人に拒否権が与えられている
和をみださないフォロアーシップがより重要
リスクを取りにくい
中程度の権力格差
中程度の個人主義

根回し
会議の前に事前に打ち合わせをする

不明瞭な意思表示
（とくに相手が気分悪くするような内容は）体面を保つように表現する
非言語的コミュニケーション
社会的、文化的に同質的な日本人は、しぐさ・表情から多くを読み取る
高文脈社会
沈黙
相手の会話にすぐには反応しない
日本人は「よく考えて対応している」と思うが、アメリカ人は「なにか偽ろうとしている」と考える
メモ
欧米ではメモが重要→日本では口頭での連絡が多い


### 統制 {#japan-control}

1. 外部統制
業績不振で株価・負債格付けが低下
敵対的買収（による経営者解任）のリスクが高まる
新規資金調達にコストが余分にかかる
日本の特徴
株式市場からの統制は弱い
←系列企業間の「株式持ち合い」による買収防止

　株式持ち合い
買収に対する意識
よく思わない文化（買い手：乗っ取り、売り手：社員（＝家族）を売る）
→1991年0.4％が最近3％に上昇（英米10％）

2. 内部統制
経営の優先順位
社員、年金受給者（OB）、取引先、銀行、株主
取締役会による統制も効きにくい
利益率が低く、企業価値（＝株式市場による評価）も低い
人事
終身雇用のため重要かつ慎重
→人事部長が役員になることがある（欧米ではまれ）

(1)　取締役会

(2)　原価低減
生産面での統制
カンバン（Just-In-Time）方式→取引先との連絡を緊密にして、品質と納期を保証する、
カイゼン→デザインや生産方式の継続的改善活動
営業面での統制
目標の市場シェア→販売価格→コスト（削減）

<span style="font-size: 150%">**参考文献**</span>

Hall, Edward T. (1977). Beyond culture. Anchor Books.（岩田慶治・谷泰（訳）(1993)『文化を超えて　新装版』阪急コミュニケーションズ.）

Hofstede, G, G. J. Hofstede, and M. Minkov (2010). Cultures and Organizations: Software of the Mind, Third Edition. McGraw-Hill Education.（日本語版　岩井八郎・岩井紀子（訳）(2013)『多文化世界　違いを学び未来への道を探る　原書第3版』有斐閣.）

Meyer, E. (2014). The Culture Map: Breaking Through the Invisible Boundaries of Global Business. PublicAffairs.（日本語版　樋口武志（訳）・田岡恵（監訳）(2015)『異文化理解力』英治出版.）

小熊英二 (2019)『日本社会のしくみ』講談社現代新書2528.
