# アジア企業の経営システム {#asia}

- 本章の構成は、以下のとおりです。

  - \@ref(asia-external)では、アジア企業の経営システムの外部要因として、\@ref(asia-culture)文化、\@ref(asia-politics)政治システム・法制度、\@ref(asia-economy)経済システムを整理します。
  
  - \@ref(asia-manager)では、アジア企業の経営者の特徴として、\@ref(asia-selection)選抜・移動、\@ref(asia-payment)報酬、\@ref(asia-education)教育を整理します。
  
  - \@ref(asia-management)では、アジア企業の経営プロセスを\@ref(asia-plan)計画、\@ref(asia-organization)組織化、\@ref(asia-command)指揮・調整、\@ref(asia-control)統制を整理します。
  
  
## アジアの文化・政治・経済 {#asia-external}

### 文化 {#asia-culture}

本講義の「アジア」
中国文明（特に儒教）の影響を受けた国・地域
中国、台湾、香港、シンガポール（75%が中国系）
韓国、北朝鮮
儒教（的価値観）
宗教ではなくむしろ慣習
秩序、序列（上下関係）を重視
親・子、夫・妻、年長・年少、支配者・市民、雇用者・従業員、教師・生徒



#### Hofstedeの指標

- 権力格差は中国80、韓国60、台湾58、香港68、シンガポール74と総じて高く、世界的にみても高いグループに位置します。

権力格差（上下関係）を受け入れやすい

  - 権力格差の高さは、儒教の「五倫（父子の親、君臣の義、夫婦の別、長幼の序、朋友の信）」に基づいています。（Edfelt (2010, p.190)、（Meyer (2014, 日本語版 pp.164-165)））
  
  - 学歴社会にもつながっており、受験戦争は厳しいです。大学院への進学率が高いです。

- 集団・個人主義は中国20、韓国18、台湾17、香港25、シンガポール20と総じて低く、世界的にみても集団意識の強いグループに位置します。

  - 家族（血縁関係）の結びつきが強いことが
  
  - 縁故（コネ）がビジネスにも影響します。
  
  - 中国では「関係（guanxi）」を築き、内集団のメンバーと見做されることがビジネス上重要となります。
  
  - アジアの集団意識は家族（血縁関係）単位で形成されていて、（企業オーナーの家族は別として）企業との関係は薄いです。
  
家族・親族、出身地・方言、出身校の関係が、日常生活やビジネスにおける信頼につながる
取引を始める前に、まず「関係」を作る


- 男性性は中国66、韓国39、台湾45、香港57、シンガポール48と。

恥・体面
恥を嫌う、体面を保つことが重要、
周囲（親・兄弟・教師・上司）の期待に応えようする

  - アメリカンドリーム「物質的成功」剛の価値が評価される一方で女性の社会進出は多く、地位も高い

- 不確実性回避は、低い（）中国30、韓国85、台湾69、香港29、シンガポール8

  - 中国は地域差があり、北部は不確実性回避の数値が高く南部は低いです。
  
  - 
華僑
華人
香港・シンガポールは不確実性回避が低い
→起業家精神が高い

- 長期指向（）中国87、韓国100、台湾93、香港61、シンガポール72

  - 短期的利益を追求、時間に厳しい、
  
  - 初対面の相手に親しく（柔らかく）接することが多く、笑顔を絶やさず、すぐにファーストネームで呼び始めたりします。（Meyer (2014, 日本語版 p.217)）
  
    - ただし、このように友好的であることは必ずしも友情とはイコールではなりません。
    
    - *長期的「関係」がない人とうまくやっていくスキル　山岸「信頼」*

- 充足的 中国24、韓国29、台湾49、香港17、シンガポール46

- アメリカは世界で最も低文脈な社会の1つです。（Meyer (2014, 日本語版 pp.60-61)）

  - 国民は世界各国からの移民で構成されています。移民はそれぞれ別々の歴史、別々の言葉、別々のバックグラウンドを持っています。
  
  - 建国以来の歴史も短いため、共有する文脈が少なくなります。

  - メッセージを伝える際は曖昧さや誤解が生じる余地をなくして、できるだけはっきりと明快に伝えることが、コミュニケーションの基本になります。

- 日本人と中国人は直接的なネガティブ・フィードバックやオープンな反論は不快に感じます。（Meyer (2014, 日本語版 p.299)）

  - 中国（と韓国）は内集団においては対立回避型である一方、外集団に対しては対立型となることがあります。（Meyer (2014, 日本語版 pp.256-257)）

  - 日本人は対立回避型であるので、中国人がとても直接的と感じることがあります。

  
- Meyer (2014, 日本語版 pp.288-290)に、日本と中国の時間に対する認識の類似点・相違点が紹介されています。

> 中国の文化では、時間に正確であることが美徳とされていて、ミーティングに遅れる場合はしっかりと謝る必要がある。ただ中国人と日本人の時間に対する認識が似ているのはここまでだ。日本人は非常にしっかりと計画を立てる。彼らは柔軟というよりは明らかに組織化されている。中国では、事前の計画がないまま、あらゆることがその場で起きる。中国人は柔軟性の最たる人々だ。明日や来週のことは考えず、今ここのことを考える文化なんだ。
> 中国人の同僚たちの働き方を見ていると、本当にただただ驚くよ。彼らは即興で計画を進めていくのに優れているんだ。（中略）前の晩に決まったことはすぐに変わる。（中略）だが結局はうまくいく。中国人は極めて柔軟なのだと一度理解すれば、自分が合わせる限りすべてうまくいく。

韓国
儒教の影響が強い
権力格差比較的高い→上下関係に厳しい学歴社会
→教育熱は東アジアで一番といわれる
個人主義低い→家族意識が強い
西洋の影響キリスト教徒が国民の1/4を占める
労働運動が闘争的







<span style="font-size: 150%">**参考文献**</span>

Hall, Edward T. (1977). Beyond culture. Anchor Books.（岩田慶治・谷泰（訳）(1993)『文化を超えて　新装版』阪急コミュニケーションズ.）

Hofstede, G, G. J. Hofstede, and M. Minkov (2010). Cultures and Organizations: Software of the Mind, Third Edition. McGraw-Hill Education.（日本語版　岩井八郎・岩井紀子（訳）(2013)『多文化世界　違いを学び未来への道を探る　原書第3版』有斐閣.）

Meyer, E. (2014). The Culture Map: Breaking Through the Invisible Boundaries of Global Business. PublicAffairs.（日本語版　樋口武志（訳）・田岡恵（監訳）(2015)『異文化理解力』英治出版.）





### 政治システム・法制度 {#asia-politics}

- 権威主義的体制 
中国 共産党（1949-）　毛沢東
台湾 国民党（1949-2000）蒋介石　
韓国 軍部出身者（1961-1993）朴正煕　
シンガポール 人民行動党（1965-）リー・クアンユー　
独裁・専制政治：強いリーダーシップ

民主化
権威主義的体制下で経済発展実現後、民主化実現　
韓国1987年　
台湾1988年　

- 開発独裁

- 歴史的に（清まで）政府は領土が広すぎて交通・通信手段が整備できず、法の執行力が不十分でした。

  - 関係性に基づく強制が必要であり、現在でもビジネスにおいて関係性の構築は重要です。

家族・慣習の重要性
  歴史的に（清まで）政府は弱い存在
→国土が広すぎて、交通・通信手段が整備できず
→法の執行力が不十分　
ビジネスの世界でも法律よりも慣習が重要
「関係」による信頼。家族が最も信頼できる

福祉
国による福祉は限定的（家族が果たす）　
労働組合
持続的な活動は少ない韓国は例外



### 経済システム {#asia-economy}

新興工業国（NIEs）
シンガポール US$53,628
香港 US$42,327
韓国 US$27,105
台湾 US$22,358
日本 US$34,513
1人当たりGDP（2015年）
中国1990年代初めから「社会主義市場経済」
経済規模は世界第2位（1位アメリカ、3位日本）
1人当たりGDP ：US$8,166 ←人口が多いため少ない



- 政府主導型経済システム
市場経済だが政府関与（支援、保護）が多い→最近は減少
（例外）香港：自由放任

- 輸出主導型経済成長
世界市場を見据えて大量生産し、輸出することで、経済発展に成功


  - 家族は最も信頼できる存在であり、家族経営によるビジネスが多いです。
  
  - 経営陣の多くを創業者一族が占めるため、とくに韓国では労使対立が激しいです。

<!-- https://www.mhlw.go.jp/wp/hakusyo/kousei/20-2/kousei-data/siryou/sh0402.html -->
<!-- https://www.mhlw.go.jp/wp/hakusyo/kousei/19-2/dl/04.pdf -->

銀行中心の金融システム
企業の負債比率高い←国有銀行も多かった企業と政府の深い関係
証券市場は存在するが十分ではない
支配権が分散するため、オーナーは株式上場を好まない →負債で資金調達し、家族経営を維持しようとする

低い税と政府支出
福祉（社会保障支出）は少ない

中小企業中心
家族経営の中小企業が多い信頼の問題
例外：韓国は財閥「チェボル」中心（ただし家族経営）

<span style="font-size: 150%">**参考文献**</span>

Hall, Edward T. (1977). Beyond culture. Anchor Books.（岩田慶治・谷泰（訳）(1993)『文化を超えて　新装版』阪急コミュニケーションズ.）

Hofstede, G, G. J. Hofstede, and M. Minkov (2010). Cultures and Organizations: Software of the Mind, Third Edition. McGraw-Hill Education.（日本語版　岩井八郎・岩井紀子（訳）(2013)『多文化世界　違いを学び未来への道を探る　原書第3版』有斐閣.）

Meyer, E. (2014). The Culture Map: Breaking Through the Invisible Boundaries of Global Business. PublicAffairs.（日本語版　樋口武志（訳）・田岡恵（監訳）(2015)『異文化理解力』英治出版.）

小熊英二 (2019)『日本社会のしくみ』講談社現代新書2528.



## アジア企業の経営者 {#asia-manager}




サムスン李氏「世襲やめる」　韓国財閥、同族経営岐路に
（https://www.nikkei.com/article/DGXMZO58842290X00C20A5FFJ000/?n_cid=SPTMG002）

### 選抜・移動 {#asia-selection}

家族経営
経営者はオーナー本人、その家族が多い

縁故主義
雇用・昇進は縁故が強く影響し、重要な役職は家族・親族が占める
このような傾向は世界各地の家族経営にみられるが、高文脈の文化でより強い傾向
信頼
経営陣（管理職）候補の重要な基準は、オーナーからの信用・信頼
→株式の所有を求めることがある
家族が最有力候補になる

韓国チェボル
大規模なため、家族だけでは経営者が足りない
信頼できる外部経営者が必要
→（オーナーと同じ）出身地・出身校が考慮される

中国国有企業
経営者は共産党からの任命
経営能力だけでなく、政治的観点からも考慮される

経営者の交代
個人間の信頼・信用が重要なため、交代は欧米に比べて少ない
経営者の採用市場では、アジアは16％、ヨーロッパは35％、アメリカは41％を占める


【有料】サムスン電子（下）分権と集権、組織に活力（アジア企業戦略解剖）
(https://www.nikkei.com/article/DGKDZO40948900Z20C12A4FF1000/)　

### 報酬 {#asia-payment}

日本経済新聞2017/8/27朝刊


https://www.google.com/search?q=%E3%82%A2%E3%82%B8%E3%82%A2%20%E7%B5%8C%E5%96%B6%E8%80%85%20%E5%A0%B1%E9%85%AC&authuser=0

### 教育 {#asia-education}

経営学部
韓国、台湾、香港、シンガポールは独立した学部をもつ
経営大学院（ビジネススクール）
欧米名門校と提携、分校設立
香港科技大学（ノースウエスタン大学）
シンガポールINSEAD（本部フランス）
シカゴ大学（シンガポール校→香港校）
中国：清華大学MBAコースもアメリカ大学と提携

留学
とくに2世経営者は、海外（大学院）留学を経験している
韓国30大チェボルの経営者の1/2はアメリカ留学経験者、1/4は日本留学経験者
学歴重視社会


https://zuuonline.com/archives/120859


大卒でも財閥系大企業でなければ年収200万円台。韓国の高学歴貧困の厳しすぎる事情
(https://hbol.jp/189601?display=b)

韓国、高学歴貧困の現状。「幼い頃の夢を叶える人なんていない」
(https://hbol.jp/189810?cx_clicks_kijishita=txt1#cxrecs_s)

これからの大学教育
(http://www.mext.go.jp/b_menu/shingi/chukyo/chukyo0/gijiroku/attach/__icsFiles/afieldfile/2013/10/16/1340415-9-2.pdf)

<span style="font-size: 150%">**参考文献**</span>

Hall, Edward T. (1977). Beyond culture. Anchor Books.（岩田慶治・谷泰（訳）(1993)『文化を超えて　新装版』阪急コミュニケーションズ.）

Hofstede, G, G. J. Hofstede, and M. Minkov (2010). Cultures and Organizations: Software of the Mind, Third Edition. McGraw-Hill Education.（日本語版　岩井八郎・岩井紀子（訳）(2013)『多文化世界　違いを学び未来への道を探る　原書第3版』有斐閣.）

Meyer, E. (2014). The Culture Map: Breaking Through the Invisible Boundaries of Global Business. PublicAffairs.（日本語版　樋口武志（訳）・田岡恵（監訳）(2015)『異文化理解力』英治出版.）

小熊英二 (2019)『日本社会のしくみ』講談社現代新書2528.

## アジア企業のマネジメント {#asia-management}

現代アジアの企業経営 - ミネルヴァ書房  
東アジアの企業経営―多様化するビジネスモデル (現代社会を読む経営学) ミネルヴァ書房
アジア企業の経営理念: 生成・伝播・継承のダイナミズム　文真堂
アジア最強の経営を考える―――世界を席巻する日中韓企業の戦い方
東アジアとアセアン諸国のコーポレート・ガバナンス 税務経理協会

なぜ韓国企業は世界で勝てるのか: 新興国ビジネス最前線
(https://www.erina.or.jp/wp-content/uploads/2014/09/20120829.pdf)
“超”格差社会・韓国

東アジアのコーポレート・ガバナンス改革
(http://www.econ.kobe-u.ac.jp/activity/publication/nenpo/pdf/kinkyo56.pdf)

日本・中国・韓国企業におけるジェンダー・ダイバーシティ経営の実情と課題
(https://www.rieti.go.jp/jp/publications/dp/14j010.pdf)

台湾企業の発展戦略書評
(https://www.osaka-ue.ac.jp/file/general/18589)

下請けなのになぜ台湾企業は強いのか
(https://president.jp/articles/-/7436)

中国の国有企業
(https://www.jri.co.jp/MediaLibrary/file/report/jrireview/pdf/6641.pdf)

中国企業の所有と経営
(https://ir.ide.go.jp/?action=repository_action_common_download&item_id=43147&item_no=1&attribute_id=26&file_no=1)

華人系企業の経営構造に対する一考察
(http://shiten.agi.or.jp/shiten/201503/shiten201503_1-14.pdf)

日韓企業「人材力」対決
(https://president.jp/category/c01406)

韓国企業と「倫理経営」
(https://www.soka.ac.jp/files/ja/20170419_153829.pdf)

https://www.nli-research.co.jp/files/topics/56098_ext_18_0.pdf?site=nli
https://www.nli-research.co.jp/files/topics/57016_ext_18_0.pdf?site=nli

https://business.nikkei.com/atcl/interview/15/238739/021200132/

中国企業の経営者意識とコーポレート・ガバナンス
(https://econ.meijigakuin.ac.jp/research/nempo/pdf/27-3.pdf)

中国企業の経営者とガバナンス
(https://meigaku.repo.nii.ac.jp/index.php?action=repository_action_common_download&item_id=299&item_no=1&attribute_id=18&file_no=1&page_id=13&block_id=21)

アジア企業のコーポレート・ガバナンスの進展
(https://www.nli-research.co.jp/files/topics/38436_ext_18_0.pdf)

### 計画 {#asia-plan}

アジア企業
家族経営の中小企業が一般的
中国の国有企業、韓国のチェボルは例外的存在
計画
直感的、柔軟→戦略的に計画を立てることは少ない
情報収集
幅広く情報を集め、直感的に行動する
→既存事業と関連性のない多角化を行うことがある
中国
税制、財産権、会計原則、外国為替、貿易政策、各種規制に不確実性が高い→計画は柔軟に見直さざるを得ない
外国との取引がある企業
欧米や日本と取引する企業は、厳しい生産納入計画、品質要求に合わせるために計画を立てている
→経営者は海外留学や海外勤務経験を有する

韓国チェボル
かつて企画部が存在し、オーナーをサポートした
→グループ全体の世界各国市場での戦略を統括

政府主導型資本主義
政府の影響
補助金、免税・減税措置、保護貿易、優先調達などで、企業行動（計画）に影響を及ぼす
銀行中心の金融システム
金融を通じた影響
証券市場は未発達、銀行の多くが国有
→融資の判断を通じて企業の投資行動（計画）に影響を及ぼす


東アジア中小企業の発展と今後の課題表6
(https://www.chukiken.or.jp/about/img/2011_02.pdf)

｢中国人､韓国人｣と日本人が働きにくいワケ2ページ
(https://toyokeizai.net/articles/amp/160021?display=b&amp_event=read-body)

異文化理解力 英治出版 ⇒　第1章

シャープ再建 鴻海流スピード経営と 日本型リーダーシップ
(https://kei-bunsha.co.jp/archives/1297)

### 組織化 {#asia-organization}

中国（華僑）の伝統
家族経営で、組織はシンプル
取引先とは「関係」でネットワーク化される
経営者ネットワーク
個人間の繋がりの連鎖で情報交換が進む
企業ネットワーク
中小企業が連携することで、世界的規模のビジネスを展開

家族経営の限界
信頼できる一族で経営陣を占める
規模拡大に限界がある
支配権を維持するために借入に依存する
財務基盤が弱く、倒産リスクが高い

韓国チェボル
独立した企業で構成されるが、ピラミッドまたは持ち合い構造の株式保有により、オーナー（一族）に支配される

チェボルと系列（旧財閥）の比較
類似点
・株式持ち合い
・グループ企業間における情報の共有
・歴史が短い（1960年代から、創業者～2,3代目）
相違点
・国民経済に占める割合が大きい
・政府からの保護支援が大きかった
・経営者はオーナー一族が多い（日本は内部昇進）
・グループ内に銀行を持たない、負債比率が高い


人的管理
https://www.jri.co.jp/page.jsp?id=15820

東アジア華人系企業グループの21世紀ビジネス戦略
http://r-cube.ritsumei.ac.jp/repo/repository/rcube/3219/be40_4tanakaA.pdf

https://www.mitsui.com/mgssi/ja/report/detail/__icsFiles/afieldfile/2018/11/14/1811c_takahashi.pdf

http://www.dl.ndl.go.jp/view/download/digidepo_8761069_po_02zhuy.pdf?contentNo=1&alternativeNo=

http://www.agi.or.jp/reports/report2014-10.pdf

台湾中小企業の柔軟性と支援政策
(http://www.eco.nihon-u.ac.jp/center/economic/publication/journal/pdf/32/32wada.pdf)

華商のネットワーキング活動と華人ネットワーク組織のブリッジ機能
(http://dl.ndl.go.jp/info:ndljp/pid/10350934?tocOpened=1)


### 指揮・調整 {#asia-command}

高い権力格差
部下には「従順、調和、服従、恭順」が期待され、上司には「（父親的）慈愛を伴った規律・権威、誠実・信頼」が期待される
親子関係の延長（家族経営）
自由なコミュニケーションが阻害される

リーダー（シップ）
権威主義的リーダー（企業：オーナー経営者）
トップダウン


- 階層主義的

- トップダウン式

この組み合わせは標準

高い不確実性回避
変化への抵抗感はある
他方、内部昇進が限定的なため、起業が多い

モチベーション
儒教的価値観（倹約、忍耐、秩序）が高度成長に寄与した


｢中国人､韓国人｣と日本人が働きにくいワケ3頁
(https://toyokeizai.net/articles/amp/160021?display=b&amp_event=read-body)

異文化理解力 英治出版 ⇒　第1章

第02回 韓国企業はなぜ強い？
(https://www.fujitsu.com/jp/group/fjm/mikata/column/oda/002.html)

韓国企業の強さの秘密は「情報」重視の経営
(https://mag.executive.itmedia.co.jp/executive/articles/1108/23/news009.html)

中国と日本の企業文化比較
(https://www.jstage.jst.go.jp/article/jasmin/2014s/0/2014s_69/_pdf/-char/ja)

### 統制 {#asia-control}

https://www.jri.co.jp/page.jsp?id=15869

内部からの統制
経営陣は家族・親族が多い→反対意見を述べる可能性のある独立した取締役、外部の監査役を避ける→利益よりも（オーナーの）支配権を重視する
オーナー経営者の暴走を止めにくい
外部からの統制
株式市場を通じた統制は少ない←株式市場が発達していない←経営者が支配権を手放したがらない
株式でなく負債（借入）に依存→国有銀行貸出はリスクよりも関係（政府関係者と経営者）が優先された
オーナー経営者の暴走を止めにくい

コストに対する感覚
香港、台湾、シンガポール（華僑）はコストや金融の効率性に対する感覚が鋭い
経営者の統制につながる
仕事の監督
基準が漠然としている→個人の責任に大きく依存
高文脈：文書化しない
人事評価
体面を保つことが重要
→部下に対しても厳しい評価をつけにくい

<span style="font-size: 150%">**参考文献**</span>

Hall, Edward T. (1977). Beyond culture. Anchor Books.（岩田慶治・谷泰（訳）(1993)『文化を超えて　新装版』阪急コミュニケーションズ.）

Hofstede, G, G. J. Hofstede, and M. Minkov (2010). Cultures and Organizations: Software of the Mind, Third Edition. McGraw-Hill Education.（日本語版　岩井八郎・岩井紀子（訳）(2013)『多文化世界　違いを学び未来への道を探る　原書第3版』有斐閣.）

Meyer, E. (2014). The Culture Map: Breaking Through the Invisible Boundaries of Global Business. PublicAffairs.（日本語版　樋口武志（訳）・田岡恵（監訳）(2015)『異文化理解力』英治出版.）

小熊英二 (2019)『日本社会のしくみ』講談社現代新書2528.
